Add file
TUNI-ITC/wiki pull request #52
Opened 2024-03-22 14:07 UTC by ShiqiZhangTuni

Add "automatically-submit-your-job-to-puhti-or-mahti.md" to main branch

2024-03-22 14:11 UTC, ilpoviertola approved these changes
Looks good! Let's add the script itself.

2024-03-22 15:25 UTC, v-iashin commented
hi @ShiqiZhangTuni thanks for making this pr. could you put the script into `docs/assets`. there is no need to create another folder in the root.

2024-03-22 15:25 UTC, v-iashin reviewed
hi @ShiqiZhangTuni thanks for making this pr. could you put the script into docs/assets. there is no need to create another folder in the root.

2024-03-22 15:26 UTC, ShiqiZhangTuni commented
Thanks, I'll upload the script to the docs/assets

2024-03-22 15:29 UTC, ShiqiZhangTuni commented
OK, finished, thanks for your waiting.

2024-03-22 15:35 UTC, v-iashin requested changes
a small change is needed.

By the way, any particular reason why is it a binary, rather than a visible .sh or .py script?

2024-03-22 15:35 UTC, v-iashin commented on docs/Technical-Notes/automatically-submit-your-job-to-puhti-or-mahti.md
> +Please firstly download the script from the following link: [auto_gpu](xxx). Then you can put it into your user folder.
link is missing :/

2024-03-22 15:39 UTC, v-iashin commented on docs/Technical-Notes/automatically-submit-your-job-to-puhti-or-mahti.md
> +Please firstly download the script from the following link: [auto_gpu](xxx). Then you can put it into your user folder.
fair enough, let's try `assets/auto_gpu`

2024-03-22 15:43 UTC, ShiqiZhangTuni commented on docs/Technical-Notes/automatically-submit-your-job-to-puhti-or-mahti.md
> +Please firstly download the script from the following link: [auto_gpu](xxx). Then you can put it into your user folder.
Thanks for your question. I understand that leaving the script in readable format gives more confidence for people to use it and it is better education for new comers. However, currently there are some CSC users applying for a lot of work at the same time, which causes a huge congestion and makes waiting time very long to start a new job. This is also the motivation that I create this script. If I open source. I'm not sure that this queue would be more crowded or not. Because such users may easily find the assertion lines and remove them to get an unlimited script.

2024-03-22 15:45 UTC, ShiqiZhangTuni commented on docs/Technical-Notes/automatically-submit-your-job-to-puhti-or-mahti.md
> +Please firstly download the script from the following link: [auto_gpu](xxx). Then you can put it into your user folder.
Yes, thanks. I just tested it roughly on my computer. It's really nice if you could try it first and give me some feedback (^_^)

2024-03-25 08:20 UTC, v-iashin approved these changes
I can't entirely agree that the script should be kept private based on the provided motivation. However, I am not sure if I should prevent it from being merged.

With this, I leave it to the end user to decide whether they'd want to run an arbitrary code on their system.

2024-03-25 11:16 UTC, ilpoviertola approved these changes
Looks good.

2024-03-25 11:16 UTC, merged